#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

pkill compton
pkill picom
pkill polybar
pkill conky
pkill pipewire
pkill pipewire-pulse
pkill spotifyd
pkill flameshot
pkill redshift
pkill copyq
pkill spotifyd
